Gajeongtongsin/Gajeongtongsin.xcodeproj/project.pbxproj
Gajeongtongsin/Gajeongtongsin/Models/Message.swift
Gajeongtongsin/Gajeongtongsin/Models/ParentUser.swift
Gajeongtongsin/Gajeongtongsin/Models/Schedule.swift
Gajeongtongsin/Gajeongtongsin/Models/ScheduleInfo.swift
Gajeongtongsin/Gajeongtongsin/Models/TeacherUser.swift

[ADD] ParentUser Data, TeacherUser Data 모델 추가 (#2)

[ADD] ParentUser Data, TeacherUser Data 모델 추가

---

Gajeongtongsin/Gajeongtongsin.xcodeproj/project.pbxproj
Gajeongtongsin/Gajeongtongsin/Global/Literal/MockData.swift
Gajeongtongsin/Gajeongtongsin/Models/Message.swift
Gajeongtongsin/Gajeongtongsin/Models/ParentUser.swift
Gajeongtongsin/Gajeongtongsin/Models/Schedule.swift
Gajeongtongsin/Gajeongtongsin/Models/TeacherUser.swift

#3 
MockData추가
-mainTeacher를 받아왔을때 ui에 원하는 방향으로 데이터를 가져오게 코드 짜주세요

[ADD] MockData추가

---

Gajeongtongsin/Gajeongtongsin.xcodeproj/project.pbxproj
Gajeongtongsin/Gajeongtongsin/Global/Base/BaseViewController.swift
Gajeongtongsin/Gajeongtongsin/Global/Literal/MockData.swift
Gajeongtongsin/Gajeongtongsin/Models/Message.swift
Gajeongtongsin/Gajeongtongsin/Models/Notification.swift
Gajeongtongsin/Gajeongtongsin/Models/ParentUser.swift
Gajeongtongsin/Gajeongtongsin/Models/Schedule.swift
Gajeongtongsin/Gajeongtongsin/Models/TeacherUser.swift

[ADD] Notification Model

---

Gajeongtongsin/Gajeongtongsin.xcodeproj/project.pbxproj
Gajeongtongsin/Gajeongtongsin/Global/Base/BaseCalenderViewCell.swift
Gajeongtongsin/Gajeongtongsin/Global/Base/BaseCollectionViewCell.swift
Gajeongtongsin/Gajeongtongsin/Screens/Parent/Reservation/Cell/CalenderViewCell.swift
Gajeongtongsin/Gajeongtongsin/Screens/Parent/Reservation/Cell/TestG.swift
Gajeongtongsin/Gajeongtongsin/Screens/Parent/Reservation/ReservationViewController.swift

[ADD] 캘린더뷰1차

---

Gajeongtongsin/Gajeongtongsin.xcodeproj/project.pbxproj
Gajeongtongsin/Gajeongtongsin/Screens/Parent/Reservation/ParentsCalenderViewController.swift
Gajeongtongsin/Gajeongtongsin/Screens/Parent/Reservation/ReservationViewController.swift

#4 
브랜치 이름변경 후 재PR
학부모 상담예약뷰 탭 분리 (상담예약 탭-(버튼)->캘린더뷰)

[ADD] 캘린더뷰 탭 분리 및 PR반영

---

Gajeongtongsin/Gajeongtongsin.xcodeproj/project.pbxproj
Gajeongtongsin/Gajeongtongsin/Screens/TabBar/TabBarViewController.swift
Gajeongtongsin/Gajeongtongsin/Screens/Teacher/Receiving/Cell/NotificationTableViewCell.swift
Gajeongtongsin/Gajeongtongsin/Screens/Teacher/Receiving/NotificationViewController.swift

#23 
데이터구조가 그대로라는 가정하에(MessageType case에 .emergency추가)짠 코드입니다.
추후에 데이터구조가 변경되면 수정할 임시코드라고 생각해주시면 될거같습니다
@KimDaeSeong8721 

[ADD] 알림창구현(긴급알림, 일반알림(쪽지, 상담신청)) - 임시코드

---

Gajeongtongsin/Gajeongtongsin/Global/Literal/MockData.swift
Gajeongtongsin/Gajeongtongsin/Models/ParentUser.swift
Gajeongtongsin/Gajeongtongsin/Screens/Parent/Reservation/ParentsCalenderViewController.swift
Gajeongtongsin/Gajeongtongsin/Screens/Teacher/Consultation/ConsultationViewController.swift

#17 
데이터 연결 완료
mock data schedule -consertingdate를 스트링->데이트로 수정하는 것에 대해 논의하고 싶음
아래 스크린샷 왼쪽처럼 슬롯 선택하고 신청하기 누르면 목데이터에 추가되고, 추가된건 print 함수 있어서 오른쪽처럼 콘솔로 확인 가능

[ADD] 학부모 캘린더뷰 데이터 연결

---

Gajeongtongsin/Gajeongtongsin.xcodeproj/project.pbxproj
Gajeongtongsin/Gajeongtongsin/Screens/Parent/Reservation/ParentsCalenderViewController.swift

빌드 컨플릭트 발생 후 수정
- 중복 viewDidLoad 와 중복 func 제거, 괄호 추가

[FIX] 파일 컨플릭트 수정

---

Gajeongtongsin/Gajeongtongsin/Global/Literal/MockData.swift
Gajeongtongsin/Gajeongtongsin/Models/Message.swift
Gajeongtongsin/Gajeongtongsin/Models/Notification.swift
Gajeongtongsin/Gajeongtongsin/Models/TeacherUser.swift
Gajeongtongsin/Gajeongtongsin/Screens/Teacher/Receiving/Cell/MessageTableViewCell.swift
Gajeongtongsin/Gajeongtongsin/Screens/Teacher/Receiving/Cell/NotificationTableViewCell.swift
Gajeongtongsin/Gajeongtongsin/Screens/Teacher/Receiving/MessageVIewController.swift
Gajeongtongsin/Gajeongtongsin/Screens/Teacher/Receiving/NotificationViewController.swift

[CHORE] Notification struct고려한 mock data 수정 및 알림창과 메세지뷰 로직 재구현

---

Gajeongtongsin/Gajeongtongsin/Screens/Parent/Sending/Cell/SentMessageTableViewCell.swift

#35 
MessageType에 .emergency사용부분삭제

[FIX] MessageType .emergency삭제

---

Gajeongtongsin/Gajeongtongsin.xcodeproj/project.pbxproj
Gajeongtongsin/Gajeongtongsin/Models/Schedule.swift
Gajeongtongsin/Gajeongtongsin/Models/ScheduleInfo.swift
Gajeongtongsin/Gajeongtongsin/Screens/Parent/Reservation/Cell/ScheduleTableViewCell.swift
Gajeongtongsin/Gajeongtongsin/Screens/Parent/Reservation/ReservationViewController.swift
Gajeongtongsin/Gajeongtongsin/Screens/Parent/Sending/Cell/SentMessageTableViewCell.swift
Gajeongtongsin/Gajeongtongsin/Screens/Parent/Sending/SendingViewController.swift
Gajeongtongsin/Gajeongtongsin/Screens/Parent/Sending/SentMessageListViewController.swift

#30 
- 전화예약의 isReserved 값 변경으로 인해 데이터 구조체 let -> var 변경 (교사가 수락하면 nil 에서 true로)
- 전화예약 테이블뷰 셀
- 전화예약 테이블뷰 컨트롤러
- delegate 연결, 테이블뷰에서 예약 건 당 섹션으로 구분, 예약 한 건 안의 3개 시간 슬롯은 row로 구분

[ADD] 학부모 전화예약 리스트 테이블뷰

---

Gajeongtongsin/Gajeongtongsin.xcodeproj/project.pbxproj
Gajeongtongsin/Gajeongtongsin/Global/Extension/UIColor+Extension.swift
Gajeongtongsin/Gajeongtongsin/Global/Protocol/CutomNavigationBarDelegate.swift
Gajeongtongsin/Gajeongtongsin/Global/UIComponent/CutomNavigationBar.swift
Gajeongtongsin/Gajeongtongsin/Screens/TabBar/TabBarViewController.swift
Gajeongtongsin/Gajeongtongsin/Screens/Teacher/Consultation/ConsultationViewController.swift
Gajeongtongsin/Gajeongtongsin/Screens/Teacher/Receiving/Cell/NotificationTableViewCell.swift
Gajeongtongsin/Gajeongtongsin/Screens/Teacher/Receiving/NotificationViewController.swift

[ADD] CustomNavigationBar & AlertView 화면전환구현

---

Gajeongtongsin/Gajeongtongsin/Screens/Teacher/Consultation/ConsultationViewController.swift
Gajeongtongsin/Gajeongtongsin/Screens/Teacher/Receiving/NotificationViewController.swift

#54 
1.캘린더에서 정해진곳이 아닌곳 터치하면 앱이 터짐
- 강제언레핑 -> 옵셔널바인딩
2.tabbar를 몇번누르면 가 사라지는 현상 발생, 알림창에 갓다가 돌아오면 tabbar가 없어짐
- willappear, willdisappear 수정

[FIX] 7월28일 버그 #54 해결

---

Gajeongtongsin/Gajeongtongsin/Global/Service/FirebaseManager.swift

[FEAT] firebase 가져오기 함수 구현

---

Gajeongtongsin/Gajeongtongsin/Screens/Teacher/Receiving/Cell/NotificationTableViewCell.swift
Gajeongtongsin/Gajeongtongsin/Screens/Teacher/Receiving/NotificationViewController.swift

제가 만들어서 사용했던 color extension에서 오류가 발생했습니다

[FIX] 컬러익스텐션오류 수정

---

Gajeongtongsin/Gajeongtongsin/Screens/Teacher/Receiving/Cell/MessageTableViewCell.swift

[CHORE] Color extension으로 수정

---

Gajeongtongsin/Gajeongtongsin/Screens/Parent/Reservation/Cell/ScheduleTableViewCell.swift
Gajeongtongsin/Gajeongtongsin/Screens/Parent/Reservation/ReservationDetailViewController.swift
Gajeongtongsin/Gajeongtongsin/Screens/Parent/Reservation/UrgentRequestViewController.swift

컬러익스텐션부분이랑 var를 let으로 바꾸라는경고창부분 수정

[FIX] 컬러익스텐션과 주의부분 수정

---

Gajeongtongsin/Gajeongtongsin/Global/Literal/MockData.swift
Gajeongtongsin/Gajeongtongsin/Global/Service/FirebaseManager.swift
Gajeongtongsin/Gajeongtongsin/Models/Notification.swift
Gajeongtongsin/Gajeongtongsin/Screens/Parent/Reservation/ParentsCalenderViewController.swift
Gajeongtongsin/Gajeongtongsin/Screens/Parent/Reservation/UrgentRequestViewController.swift
Gajeongtongsin/Gajeongtongsin/Screens/Teacher/Receiving/Cell/NotificationTableViewCell.swift
Gajeongtongsin/Gajeongtongsin/Screens/Teacher/Receiving/NotificationViewController.swift

[FEAT] 파이어베이스 알림 연결

---

Gajeongtongsin/Gajeongtongsin.xcodeproj/project.pbxproj
Gajeongtongsin/Gajeongtongsin/Screens/Login/ParentRegistrationViewController.swift

#74 
- 학부모 회원가입창에서 선생님코드 6글자수 제한
- 학부모 회원가입창에서 모든 텍스트필드이 채워질때 버튼 활성화

[FIX] 부모 회원가입창 글자수 제한 오류 해결

---

Gajeongtongsin/Gajeongtongsin/Global/UIComponent/SecondaryButton.swift
Gajeongtongsin/Gajeongtongsin/Screens/Parent/Reservation/Cell/ScheduleTableViewCell.swift
Gajeongtongsin/Gajeongtongsin/Screens/Parent/Reservation/ReservationDetailViewController.swift
Gajeongtongsin/Gajeongtongsin/Screens/Teacher/Receiving/NotificationViewController.swift

#78 
- secondary 버튼 활용하여 인디케이터 구현 (목데이터로 체크 완료)

[ADD] 전화예약 인디케이터 버튼 구현

---

Gajeongtongsin/Gajeongtongsin/Screens/Teacher/Receiving/MessageVIewController.swift

[CHORE] navigation bug fix

---

Gajeongtongsin/Gajeongtongsin/Global/Literal/Constants.swift
Gajeongtongsin/Gajeongtongsin/Global/Literal/MockData.swift
Gajeongtongsin/Gajeongtongsin/Screens/Parent/Reservation/Cell/CalenderViewCell.swift
Gajeongtongsin/Gajeongtongsin/Screens/Parent/Reservation/ParentsCalenderViewController.swift
Gajeongtongsin/Gajeongtongsin/Screens/Parent/Reservation/ReservationDetailViewController.swift
Gajeongtongsin/Gajeongtongsin/Screens/Teacher/Consultation/ConsultationViewController.swift

전화예약 모달에 하이파이 디자인을 적용했다.
전화예약 캘린더뷰 예약불가셀(이미 다른 학부모가 예약/신청한 슬롯)에 팬딩을 구현했다. -회색 셀로 표현, 클릭불가함

[ADD] 학부모 전화예약뷰 HiFi / 예약불가셀 팬딩 추가(with MockData)

---

Gajeongtongsin/Gajeongtongsin/Screens/Parent/Reservation/ReservationViewController.swift
Gajeongtongsin/Gajeongtongsin/Screens/Parent/Sending/SentMessageListViewController.swift
Gajeongtongsin/Gajeongtongsin/Screens/Profile/ProfileViewController.swift

#89 
- customNavBar 빠진 인자 추가하기

[FIX] customNavBar 에러 해결

---

Gajeongtongsin/Gajeongtongsin/Global/Service/FirebaseManager.swift
Gajeongtongsin/Gajeongtongsin/Screens/Parent/Reservation/ParentsCalenderViewController.swift
Gajeongtongsin/Gajeongtongsin/Screens/Profile/ProfileViewController.swift

[FEAT] 학부모 캘린더 pending 파이어베이스 연결

---

Gajeongtongsin/Gajeongtongsin/Screens/Parent/Reservation/ParentsCalenderViewController.swift
Gajeongtongsin/Gajeongtongsin/Screens/Parent/Reservation/UrgentRequestViewController.swift
Gajeongtongsin/Gajeongtongsin/Screens/Profile/ProfileViewController.swift

#29 
- 텍스트 미입력시 신청 불가
- 내용 없으면 placeholder로 원복

[ADD] 학부모 전화상담 신청 시 textview 수정

---

Gajeongtongsin/Gajeongtongsin/Screens/Parent/Reservation/UrgentRequestViewController.swift
Gajeongtongsin/Gajeongtongsin/Screens/Parent/Sending/SentMessageListViewController.swift
Gajeongtongsin/Gajeongtongsin/Screens/Teacher/Receiving/Cell/MessageTableViewCell.swift
Gajeongtongsin/Gajeongtongsin/Screens/Teacher/Receiving/NotificationViewController.swift

[FIX]] backgroundcolor 수정

---

Gajeongtongsin/Gajeongtongsin/Models/Message.swift
Gajeongtongsin/Gajeongtongsin/Models/Notification.swift
Gajeongtongsin/Gajeongtongsin/Models/ScheduleInfo.swift
Gajeongtongsin/Gajeongtongsin/Models/TeacherCalenderData.swift
Gajeongtongsin/Gajeongtongsin/Models/TeacherUser.swift

[FIX] 데이터구조 수정

---

Gajeongtongsin/Gajeongtongsin.xcodeproj/project.pbxproj
Gajeongtongsin/Gajeongtongsin/Global/Literal/Constants.swift
Gajeongtongsin/Gajeongtongsin/Screens/Login/ParentRegistrationViewController.swift
Gajeongtongsin/Gajeongtongsin/Screens/Parent/Reservation/Cell/ScheduleTableViewCell.swift
Gajeongtongsin/Gajeongtongsin/Screens/Parent/Reservation/ParentsCalenderViewController.swift
Gajeongtongsin/Gajeongtongsin/Screens/Parent/Reservation/ReservationDetailViewController.swift
Gajeongtongsin/Gajeongtongsin/Screens/Teacher/Consultation/ConsultationViewController.swift

#98 
- 확정하기시 크래쉬 해결
- 캘린더관련코드 리팩토링(함수공용화)

[FIX] 확정하기시 크래쉬 해결 및 캘린더쪽 코드리팩토링

---

Gajeongtongsin/Gajeongtongsin/Screens/Parent/Reservation/ReservationViewController.swift
Gajeongtongsin/Gajeongtongsin/Screens/Parent/Reservation/UrgentRequestViewController.swift
Gajeongtongsin/Gajeongtongsin/Screens/Parent/Sending/SendingViewController.swift

close #78 
긴급상담 신청 화면에서 신청 버튼 누르면 모달 사라지고 바로 토스트메시지 등장
(빨리 사라져서 캡쳐가 어렵네요)

[FEAT] 토스트메시지 구현 완료

---

Gajeongtongsin/Gajeongtongsin/Screens/Parent/Reservation/ParentsCalenderViewController.swift

- close #104 
- 키보드 입력 시 높이 조절
- 입력 완료 후 높이 원복

[FEAT] 키보드 높이 조절 구현

---

Gajeongtongsin/Gajeongtongsin.xcodeproj/project.pbxproj
Gajeongtongsin/Gajeongtongsin/Global/CalenderSlotMockData.swift
Gajeongtongsin/Gajeongtongsin/Global/Literal/Constants.swift
Gajeongtongsin/Gajeongtongsin/Models/CalenderSlotData.swift
Gajeongtongsin/Gajeongtongsin/Models/TeacherCalenderData.swift
Gajeongtongsin/Gajeongtongsin/Screens/Parent/Reservation/ParentsCalenderViewController.swift
Gajeongtongsin/Gajeongtongsin/Screens/Profile/ProfileViewController.swift
Gajeongtongsin/Gajeongtongsin/Screens/Teacher/Consultation/ConsultationViewController.swift
Gajeongtongsin/Gajeongtongsin/Screens/Teacher/Receiving/MessageVIewController.swift

#111 #114 
이전 피알을 닫고 함께 올립니다. 이전 피알에 달린 코멘트는 수정했습니다. 죄송합니다
프로필 탭에 전체 캘린더를 볼 수 있으며 수정이 가능합니다. 배경색으로 칠해진 부분은 블락된 슬롯입니다.
흰색 슬롯(활성화된 슬롯)을 탭하면 빨간색으로 표시되며 확인을 누르면 슬롯을 블락할 수 있습니다.
블락된 슬롯을 탭하면 파란색으로 표시되며 확인을 누르면 슬롯을 다시 열 수 있습니다.
확인을 누르면 교사의 캘린더 탭에 반영됩니다.
데이터는 [[Int]] 구조로 되어 있으며 calenderSlotData 변수에 저장됩니다. 해당 변수는 [[bool ...][bool...] ... ] 형태이며 2차 원소들은 섹션 묶음입니다. ([[섹션1][섹션2] ...] 형태)

[ADD] 교사 한정 슬롯 추가/삭제 구현 완료 (목데이터로 구동)

---

Gajeongtongsin/Gajeongtongsin.xcodeproj/project.pbxproj
Gajeongtongsin/Gajeongtongsin/Gajeongtongsin.entitlements
Gajeongtongsin/Gajeongtongsin/Global/Base/BaseViewController.swift
Gajeongtongsin/Gajeongtongsin/Global/Service/FirebaseManager.swift
Gajeongtongsin/Gajeongtongsin/Global/Service/PushNotificationManager.swift
Gajeongtongsin/Gajeongtongsin/Global/Supports/AppDelegate.swift
Gajeongtongsin/Gajeongtongsin/Global/Supports/Info.plist
Gajeongtongsin/Gajeongtongsin/Screens/Login/ParentRegistrationViewController.swift
Gajeongtongsin/Gajeongtongsin/Screens/Login/StartViewController.swift
Gajeongtongsin/Gajeongtongsin/Screens/Parent/Reservation/UrgentRequestViewController.swift
Gajeongtongsin/Gajeongtongsin/Screens/TabBar/TabBarViewController.swift

- close #106 
- firebase cloud messaging이랑 연결을 완료했습니다
- 긴급알림 Push Notification을 구현했습니다.

[FEAT] 긴급알림 PushNotification 구현

---

Gajeongtongsin/Gajeongtongsin.xcodeproj/project.pbxproj
Gajeongtongsin/Gajeongtongsin/Global/CalenderSlotMockData.swift
Gajeongtongsin/Gajeongtongsin/Global/Literal/Constants.swift
Gajeongtongsin/Gajeongtongsin/Global/Protocol/DateLabelViewDelegate.swift
Gajeongtongsin/Gajeongtongsin/Models/TeacherCalenderData.swift
Gajeongtongsin/Gajeongtongsin/Screens/Parent/Reservation/ParentsCalenderViewController.swift
Gajeongtongsin/Gajeongtongsin/Screens/Profile/ProfileViewController.swift
Gajeongtongsin/Gajeongtongsin/Screens/Teacher/Consultation/ConsultationViewController.swift

#109 #107 
선생님뷰와 로직이 다른 부분이 상당 있어 이전 피알 볼 때와 유의해서 살펴 주시면 감사하겠습니다
displayWeek 변수에 캘린더뷰에 띄울 주차를 지정하고, delegate의 로드 부분에서 필터링하는 방식으로 했습니다

[FEAT] 학부모 슬롯 연동 / 캘린더 이번, 다음주 구현

---

Gajeongtongsin/Gajeongtongsin.xcodeproj/project.pbxproj
Gajeongtongsin/Gajeongtongsin/Screens/Profile/ParentProfileViewController.swift
Gajeongtongsin/Gajeongtongsin/Screens/Profile/ProfileViewController.swift
Gajeongtongsin/Gajeongtongsin/Screens/TabBar/TabBarViewController.swift

- close #118
- 학부모 프로파일
- 선생님 프로파일

[ADD] parent profile view
